### ISSUE TITLE
Bootstrap 4 - active class set on wrong element

### ISSUE THREAD

**Issue by pabse** [bootstrap-ruby/bootstrap-navbar#12]
In the latest Bootstrap 4 version (v4-beta) the `active` class for the nav_item should not be set to the `li` tag. Instead it should be on the `a` tag having the class `nav-link`. See https://getbootstrap.com/docs/4.0/components/navs/#pills-with-dropdowns

[This](https://github.com/bootstrap-ruby/bootstrap-navbar/blob/master/lib/bootstrap-navbar/helpers/bootstrap4.rb#L75) is the relevant part of the code.

**Comment by manuelmeurer** [comment]
Hi, thanks for reporting this!
I don't have time to work on this right now, but would be happy for a PR! 😄 

To be honest, I think there are quite a lot of issues like this with the code for Bootstrap 4.
Or does it mostly work OK for you?

**Comment by pabse** [comment]
I'll try to open a PR for this in the next few days.

We have no other problems with it in our application. But I will check the code for possible issues 😄
