### ISSUE TITLE
navbar_item link with DELETE method

### ISSUE THREAD

**Issue by junjizhi** [bootstrap-ruby/bootstrap-navbar#20]
https://github.com/bootstrap-ruby/bootstrap-navbar/blob/ac38235d4c3bc6b22d089d463b0be6f7f6c5dfb8/lib/bootstrap-navbar/helpers/bootstrap4.rb#L50-L68

`navbar_item` accepts `link_options` keyword arguments, so to make a link that sends out a DELETE request, I had to do the following:
```ruby
navbar_item "Log Out", destroy_user_session_path, nil, "data-method" => "delete"
```
However, specifying link option `"data-method"` seems like a hack to me. [It also depends on `rails-ujs` to work](https://stackoverflow.com/a/37282409/8175889). 

Is there a better way to implement this?

**Comment by manuelmeurer** [comment]
No, this is how it should be done.
