### ISSUE TITLE
undefined method `capture'

### ISSUE THREAD

**Issue by richardselby** [bootstrap-ruby/bootstrap-navbar#21]
I'm trying to integrate this with Sinatra (1.4.8) on Ruby 2.5.1, but when just calling `navbar` I get the above error. Is there an outstanding dependency for this function?

**Comment by manuelmeurer** [comment]
Yup, my guess would be that `capture` is not available in Sinatra and you need something like `http://sinatrarb.com/contrib/capture`.
As it says in the README:
> In short: Unless you know what you're doing, do not use this gem directly in your app!

**Comment by manuelmeurer** [comment]
I think the way to go would be a `sinatra-bootstrap-navbar` gem, like https://github.com/bootstrap-ruby/rails-bootstrap-navbar and https://github.com/bootstrap-ruby/middleman-bootstrap-navbar. If you're interested to work on this, I'd be happy to add it to this org. :)

**Comment by richardselby** [comment]
Thank you!

That gem would be great - I'll see if I can get it working first. I'm quite new to ruby and sinatra; this gem is the only one I can find for generating bootstrap menus the way I'm used to, so hopefully I can make it work...
