### ISSUE TITLE
Bootstrap 5 Support broken

### ISSUE THREAD

**Issue by tpreussFN** [bootstrap-ruby/bootstrap-navbar#23]
Hello,

there's an issue in the bootstrap 5 helper. 

Please exchange 

`
                     <ul#{wrapper_attributes}>
                       #{capture(&block) if block_given?}
                     </div>
  `

to
`
                         **<ul#{wrapper_attributes}>
                           #{capture(&block) if block_given?}
                         </ul>**
`

in the navbar_dropdown function.
Thank you!

**Comment by manuelmeurer** [comment]
Thanks, @tpreussFN!
I don't have time to work on this right now, but happy to accept a PR!

**Comment by pichutan** [comment]
Hey there again (from my normal acount),

i created a PR for the change :)

**Comment by manuelmeurer** [comment]
Fixed in v3.2.1
