### ISSUE TITLE
Error trying to load gem middleman-bootstrap-navbar

### ISSUE THREAD

**Issue by Gochojr** [bootstrap-ruby/bootstrap-navbar#9]
I am using middleman static website generation gem to develop a website. I want to include the bootstrap navbar into index file so i installed middleman-bootstrap-navbar gem.

Here is my **`config.rb`**

    configure :development do
      activate :livereload
      activate :bootstrap_navbar
      ready do
      sprockets.import_asset 'bootstrap.js'
    end
    configure :build do
     end

Here is my **`gemfile`**

    # Middleman Gems
    gem 'middleman', '>= 4.0.0'
    
    # Live-reloading plugin
    gem 'middleman-livereload'
    
    gem 'middleman-compass', '>= 4.0.0'
    
    # Navigation
    gem 'middleman-bootstrap-navbar'
    gem "sass"
    gem "bootstrap-sass", "~> 3.3.6", :require => false 
    gem 'sass-rails', '>=3.2'
    gem "jquery-middleman" #Don't forget to run 'bundle install'
    gem 'sprockets-rails', '~>3.0.0'

Here is my **`all.js`**

    //= require jquery  
    //= require bootstrap-sprockets
    //= require tree .

Here is my **`site.css.sass`**

    @import "bootstrap-sprockets";
    @import "normalize";
    @import "bootstrap";
    @charset "utf-8";

I Run bundle install after installing all necessary gems and restarted my server at LiveReload ip `bundle exec middleman`. I got this error afterwards:

[screenshot of the error in mysysgit][1]

 please help.

**PS:** *Sorry I couldnt paste the error code here. That feature is not enabled in mysysgit bash.*

  [1]: http://i.stack.imgur.com/GeIaT.png

**Comment by manuelmeurer** [comment]
No need to create more than one issue. https://github.com/bootstrap-ruby/middleman-bootstrap-navbar/issues/3
